;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $b0 ;instrument $02
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $13
	.word @env2,@env0,@env12
	.byte $00
	.byte $b0 ;instrument $16
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1b
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $2c
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $2d
	.word @env6,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $31
	.word @env7,@env11,@env13
	.byte $00
	.byte $30 ;instrument $39
	.word @env8,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$cb,$cc,$cd,$ce,$cf,$00,$00
@env2:
	.byte $c2,$c4,$c6,$c6,$c7,$c7,$c8,$c7,$c6,$c5,$c5,$c4,$00,$0b
@env3:
	.byte $c8,$c6,$c5,$c4,$00,$03
@env4:
	.byte $cf,$c0,$cf,$00,$02
@env5:
	.byte $cd,$cb,$c9,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c0,$00,$0d
@env6:
	.byte $c8,$c3,$c2,$c2,$c1,$02,$c0,$00,$06
@env7:
	.byte $c7,$c9,$c6,$c2,$c1,$c0,$00,$05
@env8:
	.byte $c3,$c0,$c3,$00,$02
@env9:
	.byte $c0,$c0,$c1,$c1,$c2,$00,$04
@env10:
	.byte $c0,$c8,$cb,$cd,$ce,$00,$04
@env11:
	.byte $c0,$c1,$00,$01
@env12:
	.byte $c0,$1f,$c1,$c2,$02,$c1,$c0,$00,$02
@env13:
	.byte $ff,$00,$00


@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $80,$33,$01,$3b,$01,$3c,$00,$3b,$01,$37,$00,$85,$28,$00,$29,$00
	.byte $8d
@ref1:
	.byte $33,$01,$3b,$01,$3c,$00,$3b,$01,$37,$00,$85,$28,$00,$29,$00,$8d
@ref2:
	.byte $33,$01,$3b,$01,$40,$00,$3b,$00,$85,$37,$01,$3d,$01,$44,$00,$3d
	.byte $00,$85
@ref3:
	.byte $33,$01,$3b,$01,$40,$00,$3b,$00,$85,$33,$01,$31,$01,$33,$00,$89
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $84,$1b,$01,$23,$01,$24,$00,$23,$01,$1f,$00,$85,$10,$00,$11,$00
	.byte $8d
@ref5:
	.byte $1b,$01,$23,$01,$24,$00,$23,$01,$1f,$00,$85,$10,$00,$11,$00,$8d
@ref6:
	.byte $1b,$01,$23,$01,$28,$00,$23,$00,$85,$1f,$01,$25,$01,$2c,$00,$25
	.byte $00,$85
@ref7:
	.byte $1b,$01,$23,$01,$28,$00,$23,$00,$85,$1b,$01,$19,$01,$1b,$00,$89
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $8c,$32,$8d,$2c,$8d,$32,$85,$32,$85,$2c,$8d
@ref9:
	.byte $32,$8d,$2c,$8d,$32,$85,$32,$85,$2c,$8d
	.byte $ff,$0a
	.word @ref9
	.byte $ff,$0a
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $8a,$09,$09,$08,$85,$88,$08,$85,$8a,$08,$85,$08,$85,$08,$85,$88
	.byte $08,$8d
	.byte $ff,$0e
	.word @ref12
	.byte $ff,$0e
	.word @ref12
	.byte $ff,$0e
	.word @ref12
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $bf
@ref17:
	.byte $bf
@ref18:
	.byte $bf
@ref19:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$05
@song1ch0loop:
@ref20:
	.byte $82,$32,$00,$32,$00,$3b,$40,$89,$3a,$85,$36,$85,$3a,$85,$3c,$85
	.byte $36,$85
@ref21:
	.byte $32,$00,$32,$00,$3b,$40,$89,$3a,$85,$36,$85,$3c,$85,$3a,$8d
@ref22:
	.byte $32,$00,$32,$00,$3b,$40,$89,$3a,$85,$36,$85,$3a,$85,$3c,$85,$36
	.byte $85
@ref23:
	.byte $32,$00,$32,$00,$3b,$40,$89,$3a,$85,$36,$85,$30,$85,$32,$8d
@ref24:
	.byte $4a,$00,$4a,$00,$53,$58,$89,$52,$85,$4e,$85,$52,$85,$54,$85,$4e
	.byte $85
@ref25:
	.byte $4a,$00,$4a,$00,$53,$58,$89,$52,$85,$4e,$85,$54,$85,$52,$8d
	.byte $ff,$11
	.word @ref24
@ref27:
	.byte $4a,$00,$4a,$00,$53,$58,$89,$52,$85,$4e,$85,$48,$85,$4a,$8d
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref28:
	.byte $81,$8e,$1a,$95,$00,$85,$1a,$85,$00,$85,$22,$85,$00,$83
@ref29:
	.byte $81,$1a,$95,$00,$85,$1a,$85,$00,$85,$22,$85,$00,$83
	.byte $ff,$0d
	.word @ref29
@ref31:
	.byte $81,$1a,$95,$00,$85,$1e,$85,$00,$85,$22,$85,$00,$83
	.byte $ff,$0d
	.word @ref29
	.byte $ff,$0d
	.word @ref29
	.byte $ff,$0d
	.word @ref29
	.byte $ff,$0d
	.word @ref31
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref36:
	.byte $86,$1a,$95,$00,$85,$1a,$85,$00,$85,$22,$85,$00,$85
@ref37:
	.byte $1a,$95,$00,$85,$1a,$85,$00,$85,$22,$85,$00,$85
	.byte $ff,$0c
	.word @ref37
@ref39:
	.byte $1a,$95,$00,$85,$24,$85,$00,$85,$22,$85,$00,$85
	.byte $ff,$0c
	.word @ref37
	.byte $ff,$0c
	.word @ref37
	.byte $ff,$0c
	.word @ref37
	.byte $ff,$0c
	.word @ref39
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref44:
	.byte $8c,$08,$8d,$12,$85,$08,$85,$08,$85,$08,$85,$1a,$8d
@ref45:
	.byte $08,$8d,$12,$85,$08,$85,$08,$85,$08,$85,$1a,$8d
	.byte $ff,$0c
	.word @ref45
	.byte $ff,$0c
	.word @ref45
	.byte $ff,$0c
	.word @ref45
	.byte $ff,$0c
	.word @ref45
	.byte $ff,$0c
	.word @ref45
	.byte $ff,$0c
	.word @ref45
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
